stages:
  - test
  - build
  - deploy

before_script:
  - yarn install --ignore-scripts
  - tsc -p ./tsconfig.json
  - make stage

go_test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make 

release:
  stage: build
  script:
    - npx semantic-release
