stages:
  - test
  - build
  - deploy

before_script:
  - yarn install --ignore-scripts
  - tsc -p ./tsconfig.json
  - make stage

go_test:
  stage: test
  script:
    - make test

build:
  only:
    - master@engineering/gocrypt
  stage: build
  script:
    - make 

release:
  only:
    - master@engineering/gocrypt
  stage: deploy
  script:
    - npx semantic-release
