stages:
  - test
  - build
  - deploy
  - docs

before_script:
  - yarn install --ignore-scripts
  - tsc -p ./lib/tsconfig.json

go_test:
  before_script:
    - yarn install --ignore-scripts
    - tsc -p ./lib/tsconfig.json
    - make stage
  stage: test
  script:
    - make test

build_linux:
  only:
    - master@engineering/GoCrypt-CI
  stage: build
  script:
    - make 

build_windows:
  only:
    - master@engineering/GoCrypt-CI
  stage: build
  script:
    - make build_go_windows_x64

build_mac:
  only:
    - master@engineering/GoCrypt-CI
  stage: build
  script:
    - make build_go_mac_x64

release_bin_linux:
  only:
    - master@engineering/GoCrypt-CI
  stage: deploy
  script:
    - scp ~/build/func.so gitlab-runner@cloud.libraryofcode.org:/var/binary/linux/amd64/gocrypt-func.so
    - scp ~/build/cmd gitlab-runner@cloud.libraryofcode.org:/var/binary/linux/amd64/gocrypt-cmd

release_bin_mac:
  only:
    - master@engineering/GoCrypt-CI
  stage: deploy
  script:
    - scp ~/build/mac-x64/cmd gitlab-runner@cloud.libraryofcode.org:/var/binary/darwin/amd64/gocrypt-cmd

release_bin_windows:
  only:
    - master@engineering/GoCrypt-CI
  stage: deploy
  script:
    - scp ~/build/windows-x64/cmd gitlab-runner@cloud.libraryofcode.org:/var/binary/windows/amd64/gocrypt-cmd

release:
  only:
    - master@engineering/GoCrypt-CI
  stage: deploy
  script:
    - cp -r lib/go dist/go
    - npx semantic-release

build_docs:
  only:
    - master@engineering/GoCrypt-CI
  stage: docs
  script:
    - make build_doc

release_docs:
  only: 
    - master@engineering/GoCrypt-CI
  stage: docs
  script:
    - git pull
    - mv ~/doc/gocrypt/* /var/www/gocryptdoc
